---
title: "Curriculum Vitae - Major Jason K. Freels, PhD."
output: 
  pdf_document:
    template: ../scripts/tex/default.tex
geometry: margin=1in
---

# CONTACT INFORMATION

\large
\begin{tabbing}
Maj Jason K Freels \hspace{170pt} \= comm: \= 937.255.3636 ext. 4676\\
Air Force Institute of Technology \> DSN: \> 785.3636\\
Dept. of Systems Engineering and Management \> cell: \> 937.430.6619\\
2950 Hobson Way, Bldg. 640, Rm. 103 \> email: \>\textbf{jason.freels@afit.edu}\\ 
WPAFB, OH 45433-7765 \> url: \> \textbf{\url{https://auburngrads.github.io}}
\end{tabbing}
\normalsize

# EDUCATION

\large \justify Doctor of Philosophy in Systems Engineering \hfill _November 2013_ \newline \normalsize __Air Force Institute of Technology__

- Areas of Concentration: System Reliability, Statistics
- __Dissertation:__ "Modeling Reliability Growth in Accelerated Stress Testing"

\large \justify Masters of Science in Materials Science and Engineering \hfill _September 2006_ \newline \normalsize __Air Force Institute of Technology__ 

- Areas of Concentration: Structural Composite Materials
- __Thesis:__ "Modeling Fracture in Z-Pinned Composite Laminated using DYNA-3D"

\large \justify Bacherlors of Science in Aerospace Engineering \hfill _December 2000_ \newline \normalsize __Auburn University__ 

# ACADEMIC EXPERIENCE

\large \justify Assistant Professor \hfill September 2013 \newline \normalsize __Department of Systems Engineering and Management__

\large \justify Deputy Director \hfill _September 2013_ \newline \normalsize
__Statistical Test and Analysis Techniques Center of Excellence__

\large \justify Deputy Director \hfill _September 2013_ \newline \normalsize
__Test Science Research Consortium__ 

\large \justify Co-Founder \hfill _December 2016_ \newline \normalsize
__AFIT Data Science Lab__

\large \justify Committee Champion \hfill _January 2017_ \newline \normalsize
__Higher Learning Commission Assurance Argument__

\large \justify Member - External Discovery Sub-Committee \hfill _June 2016_ \newline \normalsize __AFIT Quality Initiative Program__ 

\newpage

# PUBLICATIONS

## Referreed Software in Publication

- Boehmke B. C. and __Freels J. K.__ (2016)\newline _learningCurve: An Implementation of Crawford's and Wright's Learning Curve Production Functions_\newline Comprehensive R Archive Network; Package version 1.0.0.

- Boehmke B. C., Montgomery R. T., Ogden J. A., and __Freels J. K.__ [ (2016)\newline _kraljicMatrix: A Quantified Implementation of the Kraljic Matrix_
\newline Comprehensive R Archive Network; Package version 1.0.0.

## Referreed Articles in Publication

- Boehmke B. C. and __Freels J. K.__ (2016)\newline _learningCurve: An Implementation of Crawford's and Wright's Learning Curve Production Functions_\newline Journal of Open Source Software, DOI: http://dx.doi.org/10.21105/joss.00202.

- Vandawaker R. M., Jacques D. R., __Freels J. K.__, Ryan E., and Huscroft J. (2016)\newline _"Health Monitoring Impact on Non-Repairable Component Supply Methods"_\newline Journal of Quality in Maintenance Engineering

- Boehmke B. C., Montgomery R. T., Ogden J. A., and __Freels J. K.__ (2016) \newline _kraljicMatrix: An R package for implementing the Kraljic Matrix to strategically analyze a firm’s purchasing portfolio_\newline Journal of Open Source Software, DOI: http://dx.doi.org/10.21105/joss.00170.

- R. M. Vandawaker, D. R. Jacques, __J. K. Freels__ (2015)\newline _"Impact of Prognostic Uncertainty in System Health Monitoring"_ \newline International Journal of Prognostics and Health Management: Vol 6 (Special Issue Uncertainty in PHM) 011; Impact Factor: 0.28

- __J. K. Freels,__, J. J. Pignatiello, R. L. Warr,and R. R. Hill (2015)\newline _"Bridging the Gap between Quantitative and Qualitative Accelerated Life Tests"_ \newline Quality and Reliability Engineering International, 31: 789–800. doi: 10.1002/qre.1636; Impact Factor: 1.457

- Collins D. H., __Freels J. K.__, Huzurbazar A. V., Warr R. L., and Weaver B. P. (2013)\newline _"Accelerated Test Methods for Reliability Prediction"_\newline Journal of Quality Technology, 45, No. 3, 244-259.; Impact Factor: 1.152\newline __Lloyd S. Nelson Award - Paper with the greatest immediate impact to practitioners__

- Collins D. H., __Freels J. K.__, Huzurbazar A. V., Warr R. L., and Weaver B. P. (2012)\newline _"Accelerated Test Methods for Reliability Prediction"_\newline Los Alamos National Lab TSC Directorate Science Highlights, 134-135, LA-UR-12-20429.

## Preprints & Submitted Works Under Review

- __Freels J. K.__ DeGroot C., and Schultz D, Buyer J. Twigg C., and Daniels J. (2016)\newline _AFIT: RMarkdown templates for theses, dissertations, reports, and journal articles_\newline Comprehensive R Archive Network; Package version 1.0.0.

- __Freels J. K.__, DeGroot C. (2016)\newline _PublicLibs: Retreive, Manipulate and Visualize U. S. Public Library Data_\newline Comprehensive R Archive Network; Package version 1.0.0.

- __Freels J. K.__, Pignatiello J. J., Warr R. L., and Hill R. R. (2016)\newline _"Maximum Likelihood Estimation for the Poly Weibull Distribution"_ \newline Quality Engineering

- __Freels J. K.__, Pignatiello J. J., Warr R. L., and Hill R. R. (2016)\newline _"Simplified Modeling of the N-Fold Weibull Distribution"_\newline Quality and Reliability Engineering International 

- Boehmke B. C. and __Freels J. K.__(2016)\newline _learningCurve: Implementing Crawford's and Wright's Learning Curve Production Functions in R_\newline Journal of Cost Analysis and Parametrics.

## Works In-Preparation (anticipated completion)

\large Referreed Journal Articles \normalsize

- Deering P. R., __Freels J. K.__, and Valencia V. V. (2017)\newline _Modeling Air Force civil infrastructure: A comparison of stochastic process models_\newline ASCE-ASME Journal of Risk and Uncertainty in Engineering Systems, Part A: Civil Engineering.

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017)\newline _SMRD: Statistical methods to accompany the text <u>Statistical Methods For Reliability Data</u>_\newline The R Journal 

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017)\newline _SMRD: Comprehensive life-data analysis in R_\newline Journal of Statistical Software

- __Freels J. K.__ and Boehmke B. R. (2017)\newline _teachingApps: App templates for teaching statistics and R programming_\newline The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017)\newline _teachingApps: Templates for building over 150 interactive shiny apps in R_\newline The Journal of Statitics Education.

- __Freels J. K.__ DeGroot C., and Schultz D., Buyer J., Twigg C., and Daniels J. (2017)\newline _AFIT: RMarkdown document templates for theses, dissertaions, reports, and journal articles_\newline The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017) \newline _evmR: Project management in R using earned value management analysis_\newline The R Journal.

- __Freels J. K.__ DeGroot C. (2017)\newline _publicLibs: Retreive, manipulate, and visualize U. S. Public Library data_\newline The R Journal.

\large Books and Book Chapters \normalsize

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2018)\newline _Statistical Methods for Reliability Data: Comprehensive life-data analysis in R_ \newline John Wiley and Sons, Inc.

\large Refereed Software \normalsize

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017) \newline _SMRD: Comprehensive analysis of reliability and survivability data_ \newline
R package version 0.10.0.

- __Freels J. K.__ and Boehmke B. R. (2017)\newline _teachingApps: Apps templates for teaching statistics, R programming, and shiny development_\newline R package version 1.0.0.

- __Freels J. K.__ and Boehmke B. R. (2017)\newline _evmR: Project analysis using earned value management_\newline R package version 1.0.0.

\newpage

# CONFERENCE PROCEEDINGS & INVITED TALKS

- __Freels, J. K.__ and Meeker, W. Q. (2017)\newline _Progress Update on R package SMRD_\newline Quality and Productivity Research Conference - Storrs, CT

- Bentz, B. R., Colombi, J. M. and __Freels, J. K.__ (2017)\newline _Attritable Design Trades: Reliability and Cost Implications for Unmanned Aircraft_\newline Annual IEEE International Systems Conference - Montreal

- __Freels, J. K.__ and Meeker, W. Q. (2017)\newline _Progress Update on R package SMRD_\newline Institute for Defense Analyses Test Science Workshop -  Springfield, VA

- Mayo, B. R., Ahner, D. A. and __Freels, J. K.__ (2015)\newline _Suitability Analysis of Continuous-Use Reliability Growth Projection Models_\newline Military Operations Research Society Symposium\newline __Richard H. Barchi Prize award winner for best presented paper__

- Holm, E. S., Valencia, V. V., Thal, A. E., __Freels, J. K.__,Badiru, A. B. (2016)\newline _Materials Testing and Cost Modeling for Composite Parts through Additive Manufacturing_\newline 13th Annual Acquisition Research Symposium -  Monterrey, CA

- Kilic H., Soni S. R., Patel R., and __Freels J. K.__ (2007)\newline _Effect of Z-Fiber Percentage on the Fracture Behavior of DCB Specimens in Mode I_\newline The 14th International Conference on Computational & Experimental Engineering and Sciences - Miami, FL

# AWARDS AND HONORS

- 2016 Richard H. Barchi Prize - Military Operations Research Society\newline (Awarded to recognize the best paper given at the MORS Symposium)

- 2013 Lloyd S. Nelson Award - American Society for Quality\newline (Awarded to recognize the technical paper providing the greatest immediate impact to practitioners)

- Lead engineer for Aeronautical System Center 2009 Team of the Year (Finalist)

- $10,000 <u>IDEA Award</u> for innovative repair design for F-16 belly door

- Lead engineer for AFMC's Supply Chain Management Team of the Year (2002)

# PROFESSIONAL ASSOCIATIONS AND CERTIFICATIONS

- Member: American Society for Quality; Statistics Division
- Member: IEEE Reliability Society
- Air Command and Staff College, Air University, Maxwell AFB, AL
- Squadron Officer School, Air University, Maxwell AFB, AL
- Aerospace Basic Course, Air University, Maxwell AFB, AL
- Aircraft Battle Damage Repair, Technician Course, 649 CLSS, Hill AFB, UT
- Aircraft Battle Damage Repair, Assessor Course, 649 CLSS, Hill AFB, UT
- Aircraft Battle Damage Repair, Engineer Course, 649 CLSS, Hill AFB, UT
- Advanced Composites Engineering Course, USAF Advanced Composites Office, UT
- Air Force Materiel Command - Supply Chain Management Course, Air University, AL
- DAWIA Certifications - SPRDE (Level III); Program Management (Level II); Test and Evaluation (Level I)

\newpage

# GRANTS, CONTRACTS, AND FUNDED PROJECTS

\vspace{12pt}

\newdimen\rhI    \rhI=0.175\textwidth
\newdimen\rhII   \rhII=0.2\textwidth
\newdimen\rhIII  \rhIII=0.075\textwidth
\newdimen\rhIV   \rhIV=0.09\textwidth
\newdimen\rhV    \rhV=0.11\textwidth
\newdimen\rhVI   \rhVI=0.1\textwidth
\newdimen\rhVII  \rhVII=0.1\textwidth
\newdimen\rowI   \rowI=0.5in
\newdimen\rowII  \rowII=1in

\begin{tabular}{lllllll}
\parbox[][\rowI][c]{\rhI}{\centering{\bfseries Project\linebreak Title}} &
\parbox[][\rowI][c]{\rhII}{\centering{\bfseries Investigators}} &
\parbox[][\rowI][c]{\rhIII}{\centering{\bfseries Role}} &
\parbox[][\rowI][c]{\rhVII}{\centering{\bfseries Research \linebreak Credit}} &
\parbox[][\rowI][c]{\rhIV}{\centering{\bfseries Sponsor}} & 
\parbox[][\rowI][c]{\rhV}{\centering{\bfseries Funded\linebreak Amount}} &
\parbox[][\rowI][c]{\rhVI}{\centering{\bfseries Dates of\linebreak Funding}}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Science of Test} & 
\parbox[][\rowII][c]{\rhII}{Ray Hill\linebreak Maj Brian Stone\linebreak Doug Hodson\linebreak Maj Jason Freels} &
\parbox[][\rowII][c]{\rhIII}{Co-PI \linebreak Co-PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 25\% \linebreak 25\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering DASD} &
\parbox[][\rowII][c]{\rhV}{\centering \$359,600} & 
\parbox[][\rowII][c]{\rhVI}{FY 2014}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Civil Engineering Applications for Direct Digital Manufacturing} & 
\parbox[][\rowII][c]{\rhII}{Maj Vhance Valencia\linebreak Lt Col Kyle Oyama \linebreak Maj Jason Freels} & 
\parbox[][\rowII][c]{\rhIII}{PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 50\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering AFCEC} &
\parbox[][\rowII][c]{\rhV}{\centering \$78,305} & 
\parbox[][\rowII][c]{\rhVI}{FY 2015}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Science of Test} & 
\parbox[][\rowII][c]{\rhII}{Ray Hill\linebreak Maj Brian Stone\linebreak Doug Hodson\linebreak Maj Jason Freels} &
\parbox[][\rowII][c]{\rhIII}{Co-PI \linebreak Co-PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 25\% \linebreak 25\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering DASD} &
\parbox[][\rowII][c]{\rhV}{\centering \$755,160} & 
\parbox[][\rowII][c]{\rhVI}{FY 2015}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Civil Engineering Applications for Direct Digital Manufacturing} & 
\parbox[][\rowII][c]{\rhII}{Maj Vhance Valencia\linebreak Lt Col Kyle Oyama \linebreak Maj Jason Freels} & 
\parbox[][\rowII][c]{\rhIII}{PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 50\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering AFCEC} &
\parbox[][\rowII][c]{\rhV}{\centering \$220,515} & 
\parbox[][\rowII][c]{\rhVI}{FY 2016}\\ 
 \hline
\parbox[][\rowII][c]{\rhI}{Science of Test} & 
\parbox[][\rowII][c]{\rhII}{Ray Hill\linebreak Maj Brian Stone\linebreak Doug Hodson\linebreak Maj Jason Freels} &
\parbox[][\rowII][c]{\rhIII}{Co-PI \linebreak Co-PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 25\% \linebreak 25\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering DASD} &
\parbox[][\rowII][c]{\rhV}{\centering \$765,000} & 
\parbox[][\rowII][c]{\rhVI}{FY 2016}\\
\hline
\parbox[][\rowII][c]{\rhI}{AFIT Data Science Lab} & 
\parbox[][\rowII][c]{\rhII}{LTC Chris Smith\linebreak Ken Bauer\linebreak Brad Boehmke\linebreak Maj Jason Freels} &
\parbox[][\rowII][c]{\rhIII}{Co-PI \linebreak Co-PI \linebreak Co-PI \linebreak Co-PI} & 
\parbox[][\rowII][c]{\rhVII}{\centering 25\% \linebreak 25\% \linebreak 25\% \linebreak 25\%} &
\parbox[][\rowII][c]{\rhIV}{\centering Army Cyber} &
\parbox[][\rowII][c]{\rhV}{\centering \$250,000} & 
\parbox[][\rowII][c]{\rhVI}{FY 2017}\\
\hline
\end{tabular}

\newpage

# STUDENTS ADVISED

\vspace{12pt}

\newdimen\rhI    \rhI=0.225\textwidth
\newdimen\rhII   \rhII=0.1\textwidth
\newdimen\rhIII  \rhIII=0.075\textwidth
\newdimen\rhV    \rhV=0.125\textwidth
\newdimen\rhVI   \rhVI=0.225\textwidth
\newdimen\rhVII  \rhVII=0.1\textwidth
\newdimen\rowI   \rowI=0.35in
\newdimen\rowII  \rowII=0.325in

\begin{tabular}{llllll}
\parbox[][\rowI][c]{\rhI}{\centering{\bfseries Student Name}} &
\parbox[][\rowI][c]{\rhII}{\centering{\bfseries Rank}} &
\parbox[][\rowI][c]{\rhIII}{\centering{\bfseries Degree}} &
\parbox[][\rowI][c]{\rhVII}{\centering{\bfseries Program}} &
\parbox[][\rowI][c]{\rhV}{\centering{\bfseries Graduation}} &
\parbox[][\rowI][c]{\rhVI}{\centering{\bfseries Faculty Role}}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Brent Russell} & 
\parbox[][\rowII][c]{\rhII}{Civilian} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2014} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Co-Advisor}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Caleb Murphy} & 
\parbox[][\rowII][c]{\rhII}{Capt.} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2014} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Co-Advisor}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{AJ Berger} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2014} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Co-Advisor}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Daniel Gartland} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2015} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Ben Mayo} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GOR} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2015} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Co-Advisor}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Gerald Jones} & 
\parbox[][\rowII][c]{\rhII}{Civilian} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2015} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\ 
 \hline
\parbox[][\rowII][c]{\rhI}{Shuxian Li} & 
\parbox[][\rowII][c]{\rhII}{Civilian} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2015} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Charles Lopez} & 
\parbox[][\rowII][c]{\rhII}{Civilian} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2015} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\ 
 \hline
\parbox[][\rowII][c]{\rhI}{Robert Vandawaker} & 
\parbox[][\rowII][c]{\rhII}{Lt. Col.} &
\parbox[][\rowII][c]{\rhIII}{\centering PhD} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Sep 2015} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Ricky Armwood} & 
\parbox[][\rowII][c]{\rhII}{Civilian} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Dec 2015} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Patrick Deering} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2016} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Co-Advisor}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Ryan Amedee} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2016} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Eric Holm} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2016} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{John Gutierrez} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GOS} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Brian Bentz} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Joseph Buyer} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Sean Murphy} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Corey Degroot} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\
\hline
\parbox[][\rowII][c]{\rhI}{Nathan Greiner} & 
\parbox[][\rowII][c]{\rhII}{Capt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GEM} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\
 \hline
\parbox[][\rowII][c]{\rhI}{Diane Schultz} & 
\parbox[][\rowII][c]{\rhII}{Civilian} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GCA} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2017} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\ 
 \hline
\parbox[][\rowII][c]{\rhI}{Abdulrahmen Alwabel} & 
\parbox[][\rowII][c]{\rhII}{RSAF} & 
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Jun 2017} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\ 
  \hline
\parbox[][\rowII][c]{\rhI}{Zachary Little} & 
\parbox[][\rowII][c]{\rhII}{Civilian} &
\parbox[][\rowII][c]{\rhIII}{\centering PhD} & 
\parbox[][\rowII][c]{\rhVII}{\centering GOS} &
\parbox[][\rowII][c]{\rhV}{\centering Sep 2017} & 
\parbox[][\rowII][c]{\rhVI}{Committee Member}\\
\hline
\parbox[][\rowII][c]{\rhI}{Daniel Timme} & 
\parbox[][\rowII][c]{\rhII}{1 Lt.} &
\parbox[][\rowII][c]{\rhIII}{\centering MS} & 
\parbox[][\rowII][c]{\rhVII}{\centering GSE} &
\parbox[][\rowII][c]{\rhV}{\centering Mar 2018} & 
\parbox[][\rowII][c]{\rhVI}{Thesis Advisor}\\
\hline
\end{tabular}

\newpage

# TEACHING EXPERIENCE

\vspace{12pt}

\newdimen\TrhI    \TrhI=0.15\textwidth
\newdimen\TrhII   \TrhII=0.35\textwidth
\newdimen\TrhIII  \TrhIII=0.35\textwidth
\newdimen\TrhIV   \TrhIV=0.135\textwidth
\newdimen\TrowI   \TrowI=0.5in
\newdimen\TrowII  \TrowII=0.5in

\begin{tabular}{llll}
\parbox[][\TrowI][c]{\TrhI}{\centering{\bfseries Course Number}} &
\parbox[][\TrowI][c]{\TrhII}{\centering{\bfseries Course Title}} &
\parbox[][\TrowI][c]{\TrhIII}{\centering{\bfseries Location}} &
\parbox[][\TrowI][c]{\TrhIV}{\centering{\bfseries Date Offered}}\\
  \hline
\parbox[][\TrowII][c]{\TrhI}{\centering SENG 585} &
\parbox[][\TrowII][c]{\TrhII}{Reliability in Systems Design} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Winter 2014}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering STAT 687} & 
\parbox[][\TrowII][c]{\TrhII}{Math of Reliability I} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Summer 2014}\\
  \hline
\parbox[][\TrowII][c]{\TrhI}{\centering SENG 585} &
\parbox[][\TrowII][c]{\TrhII}{Reliability in Systems Design} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Winter 2015}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering STAT 687} & 
\parbox[][\TrowII][c]{\TrhII}{Math of Reliability I} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Summer 2015}\\
  \hline
\parbox[][\TrowII][c]{\TrhI}{\centering LOGM 634} &
\parbox[][\TrowII][c]{\TrhII}{Reliability, Maintability, \& \linebreak Availability Engineering} &
\parbox[][\TrowII][c]{\TrhIII}{Advanced Studies in Air Mobility\linebreak Fort Dix, NJ} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Winter 2016}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering RSCH 630} &
\parbox[][\TrowII][c]{\TrhII}{Research Methods} &
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Spring 2016}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering SENG 699} &
\parbox[][\TrowII][c]{\TrhII}{Advanced R Programming} &
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Summer 2016}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering SENG 585} &
\parbox[][\TrowII][c]{\TrhII}{Reliability in Systems Design} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Fall 2016}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering STAT 687} & 
\parbox[][\TrowII][c]{\TrhII}{Math of Reliability I} & 
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Fall 2016}\\
  \hline
\parbox[][\TrowII][c]{\TrhI}{\centering LOGM 634} &
\parbox[][\TrowII][c]{\TrhII}{Reliability, Maintability, \& \linebreak Availability Engineering} &
\parbox[][\TrowII][c]{\TrhIII}{Advanced Studies in Air Mobility\linebreak Fort Dix, NJ} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Winter 2017}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering RSCH 630} &
\parbox[][\TrowII][c]{\TrhII}{Research Methods} &
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Spring 2017}\\
 \hline
\parbox[][\TrowII][c]{\TrhI}{\centering SENG 685} &
\parbox[][\TrowII][c]{\TrhII}{Reliability Engineering} &
\parbox[][\TrowII][c]{\TrhIII}{AFIT (In-Resident)} &
\parbox[][\TrowII][c]{\TrhIV}{\centering Spring 2017}\\
 \hline
\end{tabular}

\newpage

# OTHER WORK EXPERIENCE

\large \justify F-16 Lead Structural Engineer \hfill _2001 - 2004_ \newline \normalsize
__Ogden Air Logistics Center - Hill AFB, UT__

- Lead depot engineer supporting over 100 critical items used on 3,900 F-16's at 88 bases worldwide
- Responsible for the design and implementation of modifications and repair procedures to reduce maintenance costs, eliminate mission delays and enhance the performance capabilities of the F-16
- Lead F-16 engineer for Aircraft Battle Damage Repair (ABDR) mission; coordinates training activities, mentors trainees and evaluates battle damage repair procedures in ABDR exercises
- Personally designed depot repairs resulted in over 100 F-16 wings and major wing structures returned to service-saved more than $8M

\large \justify Non-Destructive Evaluation Program Manager \hfill _2006 - 2007_ \newline \normalsize
__Air Force Research Laboratory - Wright-Patterson AFB, OH__

- Directs R & D efforts and facilitates transition of novel non-destructive evaluation (NDE) technologies
- Develops broad research plan for inspection and characterization of new aircraft materials
- Lead engineer for three separate twelve-member teams charged with solving fleet-wide critical fracture issues at fuselage-wing attachment points for C-5, A-10, and KC-135 aircraft
- Initiated \$1.5M KC-135 research program to baseline fleet fatigue damage.  Results of teardown evaluation enabled a five-year fleet life extension and \$2M annual savings in maintenance costs

\large \justify Military Assistant to the Director \hfill _2007 - 2008_ \newline \normalsize
__Air Force Research Laboratory - Wright-Patterson AFB, OH__

- Oversees diverse processes for 1,200-person, $500M laboratory facilities to include four GSU's
- Prepares/directs briefings, visits, and lab tours for senior-level DOD, industry and foreign dignitaries
- Directed 1st AFRL Wargame Roadshow - Prioritized 150 research programs and $225M Science and technology budget for OSD Title 10 Wargame

\large \justify Lead Materials Engineer \hfill _2008 - 2010_ \newline \normalsize
__Aeronautical Systems Center - Wright-Patterson AFB, OH__

- Wing lead for modernization and technology transition efforts on over 500 mobility aircraft
- Provides expertise on sustainment requirements for over $44.5B in support systems acquisitions
- Lead materials engineer in Bagram AB C-17 crash recovery effort, efforts led to the successful completion of aircraft ferry flight to depot 74 days early - saved $220M jet from scrapping
- Led C-17 man-portable air defense system (MANPAD) survivability test program to reduce engine infrared signature by 75%.  Test results enabled a 42% increase in counter-measure effectiveness
- Led PACAF engine corrosion field evaluation.  Tested and qualified novel engine inlet coating material, resulted in the elimination a 168-hour overhaul
